(function(){var g=void 0,h=true,i=null,j=false,k,l=this;function aa(a,b){function c(){}c.prototype=b.prototype;a.P=b.prototype;a.prototype=new c;a.prototype.constructor=a};var ba=/[?&]__cb_debug=([^&]+)/i,ca=/:\/\/static2\.chartbeat.com\/js\/chartbeat(_[a-z]+)?\.js$/;function da(a,b){var c;c=new Image(1,1);if(b)c.onerror=b;c.src=a}function ea(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function fa(a,b){var c="",d=ga(encodeURIComponent(a));d.splice(b||5,d.length);o(d,function(a){if(a==0)a="A";else{a>>>=0;for(var b="",d;a>0;)d=a%64,b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-".charAt(d)+b,a>>>=6;a=b}c+=a});return c}
function ga(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,e=2562383102,f=271733878,n=3285377520,p=[],m,y,x,L,M,X=Math.ceil((a.length/4+2)/16),T=[X],A=0,w;A<X;A++){T[A]=[];for(m=0;m<16;m++)T[A][m]=a.charCodeAt(A*64+m*4)<<24|a.charCodeAt(A*64+m*4+1)<<16|a.charCodeAt(A*64+m*4+2)<<8|a.charCodeAt(A*64+m*4+3)}A=(a.length-1)*8;a=X-1;T[a][14]=Math.floor(A/Math.pow(2,32));T[a][15]=A&4294967295;for(A=0;A<X;A++){for(w=0;w<16;w++)p[w]=T[A][w];
for(w=16;w<80;w++)p[w]=(p[w-3]^p[w-8]^p[w-14]^p[w-16])<<1|(p[w-3]^p[w-8]^p[w-14]^p[w-16])>>>31;a=c;m=d;y=e;x=f;L=n;for(w=0;w<80;w++)M=Math.floor(w/20),M=(a<<5|a>>>27)+(M==0?m&y^~m&x:M==1?m^y^x:M==2?m&y^m&x^y&x:m^y^x)+L+b[M]+p[w]&4294967295,L=x,x=y,y=m<<30|m>>>2,m=a,a=M;c=c+a&4294967295;d=d+m&4294967295;e=e+y&4294967295;f=f+x&4294967295;n=n+L&4294967295}return[c,d,e,f,n]}
function ha(a){var b=l.navigator,c=l.window.screen,d=[b.userAgent,b.platform,(new Date).getTimezoneOffset(),c.width+c.height+c.colorDepth];o(b.plugins,function(a){d.push(a.name+a.description+a.filename+a[0].type)});b=l.performance;d=d.concat([b&&b.now?b.now():"",document.title,l.location.href,q(),ea()]);return d.concat(a||[]).join()}function r(a,b,c){var d=Array.prototype.slice,e=d.call(arguments,2);return function(){return a.apply(b,e.concat(d.call(arguments)))}}
function s(a){return typeof a!=="undefined"}function t(a){return a.replace(/^www\./,"")}function u(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)}function ia(a,b){var c=l;c.removeEventListener?c.removeEventListener(a,b,j):c.detachEvent&&c.detachEvent("on"+a,b)}function v(a){return typeof a==="number"}function z(a){return typeof a==="string"}function ja(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}
function q(){return(new Date).getTime()}function ka(a){return encodeURIComponent(a)}function B(a){return!!a&&a.constructor===Object}function la(a,b){if(!B(a)||!B(b))return a===b;var c=0,d=h;o(a,function(a,e){c++;return d=a===b[e]});if(!d)return j;var e=0;o(b,function(){e++});return c===e}function o(a,b){if(B(a)===h)for(var c in a){if(a.hasOwnProperty(c)&&b(a[c],c)===j)break}else{c=0;for(var d=a.length;c<d;c++)if(b(a[c],c)===j)break}}
function ma(a,b){var c=[];o(a,function(a,e){var f=b(a,e);c.push(f)});return c}function na(a,b){for(var c=0,d=a.length;c<d;c++)if(b(a[c]))return c;return-1}function oa(a){if(B(a)===j)return"";var b=[];o(a,function(a,d){b.push(encodeURIComponent(d)+"::"+encodeURIComponent(a))});return b.join("&")}function pa(a){z(a)||(a="");var b={};o(a.split("&"),function(a){a=a.split("::");a.length===2&&(b[decodeURIComponent(a[0])]=decodeURIComponent(a[1]))});return b}
function qa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,e=b.length;d<=e;d++)c[d]=[d];for(var f=0,n=a.length;f<=n;f++)c[0][f]=f;for(var p,m,y,d=1;d<=e;d++)for(f=1;f<=n;f++)p=d-1,m=f-1,y=c[p][m],b.charAt(p)==a.charAt(m)?c[d][f]=y:(m=c[d][m]+1,p=c[p][f]+1,y+=2,c[d][f]=Math.min(m,p,y));return c[b.length][a.length]}var ra;function sa(){}var ta=l.setInterval,C=l.clearInterval,ua=l.setTimeout,D=l.clearTimeout;
function va(a,b){var c={};o(b,function(b,e){c[b]=r(a[e],a)});return c}function wa(a){var b=[];if(!B(a))return b;for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.push(c);return b}function xa(){var a=s(l.XDomainRequest);return s(l.XMLHttpRequest)&&"withCredentials"in new l.XMLHttpRequest?new l.XMLHttpRequest:a?new l.XDomainRequest:i}
function ya(a,b,c){var d=xa();d===i?c(i):(za(function(){d.open("GET",a,h)}),d.onload=function(){d.responseText?b(d):c(d)},d.onerror=function(){c(d,"onerror")},d.timeout=1E3,d.ontimeout=function(){c(d,"timeout")},ua(function(){za(function(){d.send(i)})},0))}function za(a){try{a()}catch(b){}};function Aa(a,b,c){b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");for(var d=[],b=c.getElementsByTagName(b),c=b.length;c--;)b[c].getAttribute(a)&&d.push(b[c]);return d}function E(a,b){var c=i;b&&(c=b.getAttribute(a));if(c===i){var d=Aa(a,"*",b);d.length!==0&&(c=d[0].getAttribute(a))}return c}function Ba(a,b,c){return a===g?j:c===g&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Ba(a.parentNode,b,c)}
function Ca(a,b,c){a="page"+a+"Offset";b="scroll"+b;if(c&&(c=Aa("data-cb-scroll-element"))&&c.length)return c[0][b];if(v(l[a]))return l[a];else if(document.body&&document.body[b])return document.body[b];else if(document.documentElement[b])return document.documentElement[b];return 0}function Da(a){var b=document,b=b[b.compatMode==="CSS1Compat"?"documentElement":"body"]["client"+a]||0;window["inner"+a]&&(b=Math.min(window["inner"+a],b));return b}function Ea(){return Da("Height")}
function F(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0}function Fa(a,b,c){var d=a.ownerDocument.documentElement,e=0,f=s(c)?c+1:-1;z(b)?(b=b.toLowerCase(),c=function(a){return(a=a.nodeName)&&a.toLowerCase()===b}):c=b;for(;a&&a!==d&&e!==f;){if(c(a))return a;a=a.parentNode;e++}return i}function Ga(a){return a.nodeName&&a.nodeName.toLowerCase()==="a"&&(!a.namespaceURI||a.namespaceURI==="http://www.w3.org/1999/xhtml")}
function Ha(a){a=a||window.event;return!a?i:Fa(a.target||a.srcElement,Ga,10)}function Ia(a,b){var c=document.createElement(a);o(b,function(a,b){c.setAttribute(b,a)});return c}function Ja(a){var b=s(g)?g:{};b.src=a;a=Ia("script",b);a.setAttribute("type","text/javascript");b=document.head||document.getElementsByTagName("head")[0];s(g)?g.appendChild(a):b&&b.appendChild(a)}
function Ka(){if(s(La))return La;var a;a:{a=document.getElementsByTagName("script");for(var b=a.length-1;b>-1;b--)if(ca.test(a[b].getAttribute("src"))){a=a[b];break a}a=g}return La=s(a)}var La;function Ma(){this.Q={};this.vb=1}k=Ma.prototype;k.G=function(a,b,c){this.vb++;this.Q[a]=this.Q[a]||{};this.Q[a][this.vb]=[b,c];return this.vb};k.S=function(a){if(z(a))this.Q[a]=g,delete this.Q[a];else if(v(a)){var b=h;o(this.Q,function(c){o(c,function(d,e){if(parseInt(e,10)===a)return c[e]=g,delete c[e],b=j});return b})}};k.H=function(a,b){if(this.Q[a]){var c=arguments.length>1?Array.prototype.slice.call(arguments,1):[];o(this.Q[a],function(a){var b;a&&a.length===2&&(b=a[0],a=a[1],b.apply(a,c))})}};
k.addEventListener=function(a,b){var c=this.G(a,b);b._cbEventId=c};k.removeEventListener=function(a,b){this.Q[a]&&this.Q[a][b._cbEventId]&&this.Q[a][b._cbEventId][0]===b&&this.S(b._cbEventId)};var G=new Ma,Na="o",Oa={G:Na,S:"f"},Pa="a";var H={};
H.q=function(){H.jb?H.Ka("pageload"):(H.cc=[{target:l,event:"scroll"},{target:document.body,event:"keydown"},{target:document.body,event:"mousemove"},{target:l,event:"resize"},{target:document.body,event:"mousedown"}],H.Ta=i,H.ub=j,H.ta=i,H.Qb={},H.Ua={},o(H.cc,function(a){var b=a.event;u(a.target,b,function(a){H.Ka.call(H,b,a)})}),G.G("f",function(){H.Ka("focus")}),H.Ka("pageload"),u(document.body,"click",function(a){(a=Ha(a))&&G.H("c",a)},h),u(document.body,"contextmenu",function(a){(a=Ha(a))&&
G.H("r",a)}),H.jb=h)};H.fc=function(){var a,b=H.Qb.keydown;if(b===g)return j;b=q()-b;return b<=(a||15E3)&&b>=0};H.qa=function(a,b){var c=H.Ua[a];if(!c)return"";var b=b||q(),d,e=0;o(c,function(a){d=Math.floor((b-a)/1E3);d>=0&&d<16&&(e|=1<<d)});c=("0000"+e.toString(16)).slice(-4);return c=="0000"?"":c};H.Lc=function(){H.Ua={}};H.Cb=100;H.Ka=function(a,b){if(!b)b=window.event;if(b&&a==="keydown"){var c=b.keyCode?b.keyCode:b.which;if(c===32||c>36&&c<41)a="scroll"}H.Qc(a);H.Ta===i?H.Yb():H.ub=h};
H.Qc=function(a){var b=q();H.Qb[a]=b;var c=H.Ua[a];c?c.length<2?c.push(b):c[c.length-2]>b-1E3?c[c.length-1]=b:c.push(b):c=[b];c.length>32&&c.shift();H.Ua[a]=c};H.Yb=function(){H.Ta=ua(H.jc,H.Cb);G.H(Pa);H.ta!==i&&D(H.ta);H.ta=ua(function(){G.H("i");D(H.ta);H.ta=i},5E3+H.Cb)};H.jc=function(){D(H.Ta);H.Ta=i;if(H.ub)H.ub=j,H.Yb()};var Qa,Ra,Sa,Ta,Ua;(function(){var a,b;o(["","moz","o","ms","webkit"],function(c){a=(c+"Hidden").charAt(0).toLowerCase()+(c+"Hidden").slice(1);if(typeof l.document[a]==="boolean")return b=c,j});b!==g&&(Ta=a,Ua=(b+"VisibilityState").charAt(0).toLowerCase()+(b+"VisibilityState").slice(1),Sa=b+"visibilitychange")})();var Va=j;function Wa(){Va=Ua&&l.document[Ua]==="prerender"?h:j}function Xa(){Ra=h;G.H("f")}function Ya(){Ra=j;G.H("b")}
function Za(a,b,c){l.addEventListener?l.addEventListener(a,c,j):l.document.attachEvent&&l.document.attachEvent(b,c)}function $a(){var a=h;l.document.hasFocus&&(a=l.document.hasFocus());var b=j;Ta&&(b=l.document[Ta]);return a&&!b}function ab(){$a()?Xa():Ya()}function bb(a){Wa();if(Va){var b=j,c=function(){b||(Wa(),Va||(b=h,a(),l.window.setTimeout(function(){l.document.removeEventListener(Sa,c,j)},100)))};l.document.addEventListener(Sa,c,j)}else a()};function I(){this.k=l._sf_async_config||{};this.Ib=r(this.Ub,this)}I.prototype.q=function(){this.Ma=0};I.prototype.Ub=function(){};I.prototype.za=function(a){Va||da(a,this.Ib)};I.prototype.Z=function(){this.Ib=i};function cb(a){var b={};a&&(a.charAt(0)=="?"&&(a=a.substring(1)),a=a.replace("+"," "),o(a.split(/[&;]/g),function(a){a=a.split("=");b[decodeURIComponent(a[0])]=decodeURIComponent(a[1])}));return b}function db(a,b){var c="",d=l.location.href.split("?");if(d.length){var d=cb(d[1]),e=b||a;d[e]&&(c=d[e])}return c}function eb(a,b){return!b?h:a==="http:"&&b==="80"||a==="https:"&&b==="443"}
function fb(a,b){var c=[];o(b,function(b){var e=a[b];s(e)&&(Object.prototype.toString.call(e)==="[object Array]"?o(e,function(a){c.push(b+"="+a)}):B(e)?o(e,function(a,b){c.push(b+"="+a)}):((e+"").length||b=="r")&&c.push(b+"="+e))});c.push("_");return c.join("&")}
function gb(a){var b={hostname:"",pathname:"",search:"",protocol:"",port:"",hash:""};if(!a)return b;var c=document.createElement("a"),d=l.location;if(!/^https?:/.test(a)&&a.indexOf("javascript:")!==0)if(a.indexOf("//")===0)a=d.protocol+a;else if(a.indexOf("/")===0)var e=eb(d.protocol,d.port)?"":d.port,a=d.protocol+"//"+d.hostname+(e?":"+e:"")+a;else{var e=document.baseURI||d.href,f=e.indexOf("?");f===-1&&(f=e.indexOf("#"));if(f===-1)f=e.length;f=e.lastIndexOf("/",f);a=f===-1?"/"+a:e.substr(0,f)+"/"+
a}c.href=a;b.hostname=c.hostname;b.pathname=c.pathname;b.search=c.search;b.protocol=c.protocol;b.port=c.port;b.hash=c.hash;if(b.pathname.charAt(0)!=="/")b.pathname="/"+b.pathname;if(b.hostname==="")b.hostname=d.hostname;if(b.protocol==="")b.protocol=d.protocol;if(b.protocol==="javascript:")b.pathname="",b.hostname="",b.port="",b.hash="";if(eb(b.protocol,b.port)||b.port==="0")b.port="";return b}
function hb(a){var b=a.protocol;a.hostname&&(b+="//"+a.hostname,a.port&&(b+=":"+a.port));return b+a.pathname+a.search+a.hash}function ib(){var a=0,b=(l.location.search||"").match(ba);b&&b[1]&&(a=parseInt(b[1],10));return a};function J(a,b,c){a[b]=a[b]||c}function jb(a,b){for(var c=l[a]||[];c.length;)b(c.shift());l[a]={push:b}}function kb(a){o(document.getElementsByTagName("script"),function(b){if(b.src.match(/chartbeat.js/))return b=cb(b.src.split("?")[1]),J(a,"uid",b.uid),J(a,"domain",b.domain),j})}function lb(a,b){return a[b]?encodeURIComponent(a[b]):""}function mb(a){var b={};o(a,function(a,d){d.charAt(0)=="_"&&(b[d]=a)});return b};function nb(a){var b=a===document.documentElement?a.scrollHeight:a.offsetHeight,c=a.offsetWidth;if(b<=1||c<=1){var d=ob(a,["overflow","overflow-x","overflow-y"]);d.overflow==="hidden"||d["overflow-x"]==="hidden"||d["overflow-y"]==="hidden"||o(a.getElementsByTagName("iframe"),function(a){var d=a.offsetHeight,a=a.offsetWidth;if(d>1&&a>1)return b=d,c=a,j})}return{height:b,width:c}}function pb(a){a=nb(a);return a.height*a.width}
function qb(a){var b;"contains"in document.documentElement&&!document.documentElement.contains(a)?b=j:(b=nb(a),b=b.height>1&&b.width>1);if(!b)return j;b=ob(a,["visibility","display","overflow","opacity"]);if(b.visibility=="hidden"||b.display=="none"||b.opacity=="0")return j;if(b.overflow=="hidden"&&(a.offsetHeight==0||a.offsetWidth==0))return j;b=h;for(var c=a.parentElement;c&&b;){var d;if(c.scrollHeight===c.clientHeight&&c.scrollWidth===c.clientWidth)d=j;else{var e=ob(c,["overflow","overflow-x",
"overflow-y"]);d=e.overflow;var f=e["overflow-x"],e=e["overflow-y"];d=d==="auto"||d==="scroll"||f==="auto"||f==="scroll"||e==="auto"||e==="scroll"}d&&(b=rb(a,c));c=c.parentElement}return b&&rb(a,i)}function rb(a,b){var c,d;if(b){var e=nb(b);c=e.width;d=e.height}else c=Da("Width"),d=Ea();var f=nb(a),e=f.height,f=f.width,n=sb(a,b),p=n.y,n=n.x;c=Math.min(n+f,f,c,c-n);d=Math.min(p+e,e,d,d-p);if(c<0||d<0)return j;e*=f;return c*d>=(e>=242500?0.3:0.5)*e}
function sb(a,b,c){var d=a.offsetLeft,e=a.offsetTop,f=tb(a);d+=f.x;e+=f.y;for(var n=j,p=c?0:Ca("X","Left",g),m=c?0:Ca("Y","Top",g),f=a.offsetParent;a&&a!==b&&a!==document.body;){if(a===f)f=tb(a),d+=a.offsetLeft+f.x,e+=a.offsetTop+f.y,f=a.offsetParent;c||(d-=a.scrollLeft,e-=a.scrollTop);if(ob(a,["position"]).position==="fixed"){n=h;break}a=a.parentElement}c||(d-=b?b.scrollLeft:p,e-=b?b.scrollTop:m);n&&(d+=p,e+=m);return{x:d,y:e}}
function ob(a,b){var c={},d,e;l.getComputedStyle?d=l.getComputedStyle(a,i):a.currentStyle?e="currentStyle":a.style&&(e="style");o(b,function(b){c[b]=d?d[b]||d.getPropertyValue(b):a[e][b]});return c}var ub=/matrix(3d)?\((.*)\)/;function tb(a){var b={x:0,y:0},a=ob(a,["transform"]).transform;if(!z(a))return b;var c=a.match(ub);if(!c)return b;var a=c[2].split(", "),d;s(c[1])?(c=12,d=13):(c=4,d=5);b.x=parseInt(a[c],10);b.y=parseInt(a[d],10);return b};var K={},vb={cb:"g"};K.Eb={IDLE:0,cd:1,Vc:2,Db:3};K.U=0;K.q=function(){if(!K.jb)G.G(Pa,K.rc,K),G.G("i",K.uc,K),G.G("f",K.tc,K),G.G("b",K.sc,K),K.jb=h};K.cb=function(){return K.U};K.rc=function(){K.U===1?K.ca(3):K.U===0&&K.ca(2)};K.uc=function(){K.U===3?K.ca(1):K.U===2&&K.ca(0)};K.tc=function(){(K.U===0||K.U===2)&&K.ca(3)};K.sc=function(){K.U===3?K.ca(2):K.U===1&&K.ca(0)};K.ca=function(a){K.U=a;G.H("s",a)};function wb(a,b){this.eb=a||g;this.xa=b||g;this.ja=this.X=0;this.ib=r(this.ib,this)}k=wb.prototype;k.q=function(){this.ja=this.X=0;this.Ba=i;this.Nc=G.G("s",this.ra,this);this.ra(K.cb())};k.ra=function(a){C(this.Ba);this.Ba=i;if(a===K.Eb.Db)this.Ba=ta(this.ib,1E3)};k.ib=function(){if(this.eb===g||this.eb())this.X++,this.ja++,this.xa&&this.xa()};k.terminate=function(){C(this.Ba);this.Ba=i;G.S(this.Nc)};k.Z=function(){this.terminate();this.xa=this.eb=g};function N(a,b){I.call(this);this.M=a;this.Hc=b;this.ea=a.getAttribute("data-cb-ad-id")||a.id||"";this.wb=r(this.wb,this);this.Fb=0;this.Wa=xb;var c=this;this.$=new wb(function(){yb(c);return qb(c.O)},r(this.xa,this));zb&&this.Fa();this.q()}var zb;aa(N,I);
N.prototype.q=function(){N.P.q.call(this);this.Fb++;this.Wb=j;this.N={};this.N.campaignId="";this.N.creativeId="";this.N.placementId="";this.N.siteId="";this.N.server_height="";this.N.server_width="";this.N.lineId="";this.O=this.M;this.Ja=this.kb=this.hb=this.mb=this.$a=j;this.Za={zc:j,frame:j};yb(this);this.Xa=Ab;this.bc=j;this.zb={};this.$.q();this.$b=j;this.Ea=0;this.la=i;this.Tc=G.G("s",this.ra,this);this.ra(K.cb())};
N.prototype.Fa=function(){var a=this;this.fa=new zb(this.ea,function(){return{adContainer:a.M,creativeContainer:a.O,viewableIntervals:a.Ea,creativeScenarios:a.Za,adPingData:Bb(a)}})};var xb=0,Ab=0;N.prototype.ra=function(a){if(this.la!==i)C(this.la),this.la=i;this.Ea=0;if(a===K.Eb.Db)this.la=ta(this.wb,100)};N.prototype.wb=function(){if(qb(this.O)){if(this.Ea++,this.Ea>=10)this.$b=h,Cb(this),G.H("p")}else this.Ea=0;this.fa&&this.fa.update()};function Cb(a){G.S(a.Tc);C(a.la);a.la=i}
N.prototype.xa=function(){G.H("e",this);this.bc&&G.H("z",this.zb,1);this.fa&&this.fa.update()};var Db={300:{250:1,600:1,1050:1},180:{150:1},160:{600:1},728:{90:1},970:{90:1,66:1,250:1,415:1,550:1},120:{60:1},88:{31:1},62:{88:1},196:{31:1}};
function yb(a){var b=l._sf_async_config;if(b&&(b=b.creativeDetection,b===j||z(b)&&b!=="iab"))return;var c=pb(a.M);if(a.O!==a.M)if(b=pb(a.O),b>c||b===0)a.O=a.M;else if(b>0)return;o(["iframe","embed","object","img","div"],function(b){o(a.M.getElementsByTagName(b),function(b){var d=nb(b);if(!(d.height*d.width>c)&&Db[d.width]&&Db[d.width][d.height])return a.O=b,a.Za.zc=h,j});return a.O===a.M})}
function Eb(a,b,c){if(b.exclude)a.$a=h;if(b.noRefresh)a.mb=h;var d=b.roadblock;a.Ja=d==="master";a.kb=a.Ja||d==="companion";a.N=b;a.hb=!!c;if(a.hb){var d=h,e=l._sf_async_config;if(e&&(e=e.creativeDetection,e===j||z(e)&&e!=="iframe"))d=j;if(d&&pb(c)>0)a.O=c,a.Za.frame=h}G.H("p");if(b=b.vizu)a.bc=h,a.zb=pa(b),G.H("z",a.zb,a.$.X)}function O(a,b){return a.N&&s(a.N[b])?a.N[b]:""}var P="engagedSeconds",Fb={$c:"id",Zc:P,Wc:"campaignId",Xc:"creativeId",bd:"placementId",Yc:"element"};
function Gb(a){var b={};b.id=a.ea;b[P]=a.$.X;b.campaignId=O(a,"campaignId");b.creativeId=O(a,"creativeId");b.placementId=O(a,"placementId");return b}
function Bb(a){var b={};b.at=a.gd;b.an=a.ea;b.as=a.Ma;b.aj=a.Wb?0:240;b.aE=a.$.X;if(a.O){var c=sb(a.O,g,h);b.ax=c.x;b.ay=c.y;c=nb(a.O);b.aw=c.width;b.ah=c.height}b.aV=a.$b;b.ao=a.Fb;b.ac=O(a,"campaignId");b.av=O(a,"creativeId");b.aP=O(a,"placementId");b.aS=O(a,"siteId");b.aW=O(a,"server_width");b.aH=O(a,"server_height");b.aL=O(a,"lineId");b.exclude=a.$a;b.am=a.Wa;b.aR=a.Xa;return b}
function Hb(a){var b=encodeURIComponent(a.an),c=a.aE,d=a.ax,e=a.ay,f=a.aw,n=a.ah,p=encodeURIComponent(a.av||""),m=encodeURIComponent(a.ac||""),y=encodeURIComponent(a.aP||""),x=encodeURIComponent(a.aS||""),L=encodeURIComponent(a.aH||""),M=encodeURIComponent(a.aW||""),X=encodeURIComponent(a.aL||""),T=a.ao,A=a.aR,w=a.am,Cc=a.aV?"1":"0";a.exclude&&(m="");return b+"="+[c,d,e,f,n,m,p,T+"."+A,Cc,y,x,L,M,X,w].join("::")}
N.prototype.Ca=function(){if(!this.hb){var a=this.M,b={};b.campaignId=E("data-cb-campaign-id",a)||"";b.creativeId=E("data-cb-creative-id",a)||"";b.placementId=E("data-cb-placement-id",a)||"";b.siteId=E("data-cb-site-id",a)||"";b.server_height=E("data-cb-creative-height",a)||"";b.server_width=E("data-cb-creative-width",a)||"";b.lineId=E("data-cb-line-id",a)||"";b.roadblock=E("data-cb-roadblock",a)||"";if(E("data-cb-exclude",a))this.$a=h;if(E("data-cb-no-refresh",a))this.mb=h;la(b,this.N)||Eb(this,
b)}};N.prototype.refresh=function(){this.Wb=h;Cb(this);this.$.terminate();this.q()};N.prototype.Z=function(){N.P.Z.call(this);Cb(this);C(this.fd);this.$.Z();this.Hc=this.N=this.O=this.M=this.$=i;this.fa&&this.fa.dispose()};var Q={};Q.D=function(a){var b=l._sf_async_config;if(!a&&b&&b.noCookies)return i;if(Q.D.Ya!==g)return Q.D.Ya;var a=q()+"",c,d;try{if((d=l.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return Q.D.Ya=d}catch(e){}return Q.D.Ya=i};Q.B=function(a){var b=Q.D();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&q()>c)?(Q.remove(a),""):b.getItem(a)||""};
Q.create=function(a,b,c){var d=Q.D();if(d){var e=new Date;e.setTime(q()+c*1E3);try{d.setItem(a,b),d.setItem(a+"_expires",e.getTime())}catch(f){}}};Q.remove=function(a){var b=Q.D();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};function Ib(){this.lc=l._sf_async_config||{};this.gb=r(this.gb,this);this.fb=r(this.fb,this);this.Oa=Jb;this.Jb=[]}(function(a){a.Lb=function(){return a.Ac||(a.Ac=new a)}})(Ib);var Kb=["placementId","id",P],Jb=0;function Lb(){var a=Ib.Lb(),b=Q.B("_cba_rc");b?Mb(a,b):ya("https://adsapi.chartbeat.com/advertising/adrefresh/config/cache/v1/?host="+encodeURIComponent("ads."+a.lc.domainAd),a.gb,a.fb)}
function Mb(a,b){if(b){var c=b.split("::");if(c[0].length===1&&(a.Oa=parseInt(c.splice(0,1),10),isNaN(a.Oa)))a.Oa=Jb;a.Jb=ma(c,function(a){var b={};o(a.split("<>"),function(a,c){if(a){var d=Kb[c];b[d]=d===P?parseInt(a,10):a}});return b})}G.H("g")}Ib.prototype.gb=function(a){a=a.responseText;Mb(this,a);Q.create("_cba_rc",a,43200)};Ib.prototype.fb=function(){G.H("g")};var R={};R.ic=function(){try{R.create("_cb_test","1",1);var a=R.B("_cb_test");R.remove("_cb_test");return a==="1"}catch(b){return j}};R.B=function(a){a+="=";var b="";o(document.cookie.split(";"),function(c){for(;c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return b=c.substring(a.length,c.length),j});return b};
R.create=function(a,b,c){var d=l._sf_async_config;if(d&&d.noCookies)return"";d=new Date;d.setTime(q()+c*1E3);a=a+"="+b+("; expires="+d.toGMTString())+"; path=/";return document.cookie=a};R.remove=function(a){return R.B(a)?R.create(a,"",-86400):""};function Nb(a){this.Na=a||"";this.kc=Q.D()!==i||R.ic();this.tb=j;Ob(this)}k=Nb.prototype;k.isSupported=function(){return this.kc};
function Ob(a){if(!R.B("_cb_ls")){var b=Q.D()!==i,c=R.B("_SUPERFLY_nosample");c&&o(["","_v_","_p_"],function(b){a.create(b+"_SUPERFLY_nosample",c,600,h)});var d=R.B("_chartbeat3");d&&(a.create("_v__chartbeat3",d,2592E3,h),R.remove("_chartbeat3"));b&&((b=R.B("_chartbeat2"))&&a.create("_chartbeat2",b,94608E3,h),(b=R.B("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,94608E3,h),(b=R.B("_chartbeat5"))&&a.create("_chartbeat5",b,60,h));R.create("_cb_ls","1",2592E3)}}
function Pb(a){var b=a.tb;a.tb=j;return b}k.create=function(a,b,c,d){a=d?a:this.Na+a;(Q.D()?Q:R).create(a,b,c);Q.D()&&R.create(a,b,c)};k.update=function(a,b,c,d,e,f,n){a=d?a:this.Na+a;e=z(e)?e:"::";d=(d=this.B(a,h))?d.split(e):[];if(n&&d.length){var p=n(b),m=na(d,function(a){return n(a)===p});m!==-1&&d.splice(m,1)}v(f)&&d.length>=f&&d.splice(0,d.length-f+1);d.push(b);this.create(a,d.join(e),c,h)};
k.B=function(a,b){var a=b?a:this.Na+a,c=(Q.D()?Q:R).B(a);if(!c&&Q.D()&&(c=R.B(a))&&R.B("_cb_ls")){this.tb=h;var d;switch(a){case "_SUPERFLY_nosample":d=600;break;case "_chartbeat4":d=3600;break;case "_cb_cp":d=3600;break;case "_chartbeat3":d=2592E3;break;default:d=94608E3}Q.create(a,c,d)}return c};k.remove=function(a,b){a=b?a:this.Na+a;(Q.D()?Q:R).remove(a);Q.D()&&R.remove(a)};function Qb(a){var b=i;if(a&&(b=Rb()))return b;var c=l.location,b=S(c.pathname),a=c.search||"",a=a.replace(/PHPSESSID=[^&]+/,""),d=/&utm_[^=]+=[^&]+/ig;(c=d.exec(c.search))&&(a=a.replace(d,""));d=/\?utm_[^=]+=[^&]+(.*)/i;(c=d.exec(a))&&(a=a.replace(d,c[1]!=""?"?"+c[1]:""));return b+a}function Rb(){var a=i;o(document.getElementsByTagName("link"),function(b){if(b.rel=="canonical")return b=gb(b.href),a=S(b.pathname)+b.search+b.hash,j});return a}
for(var Sb={},Tb=0;Tb<81;Tb++)Sb["0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-._~!$&'()*+,;=:@[]".charCodeAt(Tb)]=h;function Ub(a,b){if(a==="%")return"%25";var c=parseInt(b,16);return Sb[c]?String.fromCharCode(c):"%"+b.toUpperCase()}function S(a){if(!z(a))return a;a=a.replace(/%([0-9A-Fa-f]{2})?/g,Ub);return a=a.replace(/[^0-9A-Za-z\-._~!$&'()*+,;=:@\/\[\]?#%]+/g,encodeURIComponent)};function U(){I.call(this);this.ga=[];this.F=new Nb(this.Zb);this.J=new wb;this.pb=r(this.ya,this);u(l,"unload",this.pb);bb(r(this.q,this))}aa(U,I);k=U.prototype;k.Qa=h;
k.q=function(){U.P.q.call(this);this.Ha=this.ba=0;this.da=q();this.Aa=fa(Vb(this));this.ka=h;this.lb=72E5;if(this.Qa){var a=+this.k.sessionLength;if(!isNaN(a))this.lb=a*6E4}a=Wb(Xb);if(!a){var a=[],b=this.F.B("_chartbeat2",h);b.length>0&&(a=b.split("."));a.length>4&&(a=[]);var b=q(),c=b-+(a[1]||0),d=b-+(a[2]||0),e=Yb,c=a[0]&&c>18E5&&d<2592E6?0:1;V()[e]=c;c="1";d=a&&+a[2];e=a&&a[3];if(a&&d&&e)if(c=Math.abs((ja(b)-ja(d))/864E5)){c=Math.min(c,16)-1;for(d="";c--;)d+=0;c=(e+d+"1").slice(-16)}else c=e;
e=c;a[0]||(a[0]=this.k.utoken||fa(Vb(this),3),a[1]=b);a[2]=b;a[3]=e;this.k.utoken=this.Da;this.F.create("_chartbeat2",a.join("."),94608E3,h);b=Xb;V()[b]=a}this.ed=a.join(".");var f;e=+a[1];c=+a[2];if((b=a[3])&&e&&c)f=(Math.min((Math.abs((ja(c)-ja(e))/864E5)||0)+1,16,b.length)-1).toString(16),f+=("0000"+parseInt(b,2).toString(16)).slice(-4);this.Kb=f;this.Dc=Wb(Yb,1);this.Da=a[0];this.J.q();K.q();H.q();Qa||(Ra=$a(),Sa&&l.document.addEventListener&&l.document.addEventListener(Sa,ab,j),Za("focus","onfocusin",
Xa),Za("blur","onfocusout",Ya),Ra&&Xa(),Qa=h);this.va=0;this.ec=G.G(Pa,this.ob,this)};function Zb(a){if(!a.F.B("_SUPERFLY_nosample")&&!Va)a.Cc?a.Ra():(a.Cc=h,!l._sf_async_config&&!l._cbq?(a.La=r(a.Ra,a),u(l,"load",a.La)):a.Ra())}k.Ra=function(){var a=l._sf_startpt,b=l._sf_endpt;if(v(a))this.qb=v(b)?b-a:q()-a;H.q();a=r(this.wa,this);this.Nb=ta(a,15E3);this.wa()};
k.wa=function(){var a=this.J.ja,a=this.k.reading&&+this.k.reading||a>0;if(this.Ha<this.ba&&!a)this.Ha++;else{var b;if(ra===g)b=l.navigator.userAgent,ra=b.indexOf("AppleWebKit")>0&&b.indexOf("FBIOS")>0;b=ra;b&&!a?this.Ha++:(a?this.ba=0:$b(this),this.Ha=0,this.ga.push(0),this.ga.length>18&&this.ga.shift(),this.Qa&&q()-this.da>=this.lb?this.terminate():this.Y())}};
function ac(a){var b={};b.g=a.k.uid;b.g0=lb(a.k,"sections");b.g1=lb(a.k,"authors");b.g2=lb(a.k,"zone");b.g3=lb(a.k,"sponsorName");b.g4=lb(a.k,"type");!a.k.noCookies&&a.F.isSupported()?b.n=a.Dc:b.nc=1;b.c=Math.round((q()-a.da)/600)/100;b.E=a.J.X;var c=bc(a);a.va=Math.max(a.va,c);b.x=c;b.m=a.va;b.y=F("Height");b.o=F("Width");b.w=Ea();b.b=a.qb?a.qb:"";if(a.Kb)b.f=a.Kb;b[""]=mb(a.k);b.t=a.Aa;b.V=64;b.tz=(new Date).getTimezoneOffset();b.sn=a.Ma;return b}
k.Ub=function(){this.ga.push(1);var a=0;o(this.ga,function(b){a+=b});a<3?(this.ka=h,$b(this)):(this.terminate(),this.F.create("_SUPERFLY_nosample","1",600))};k.ya=function(){};k.ob=function(){var a=bc(this);this.va=Math.max(this.va,a)};function bc(a){return Ca("Y","Top",!!a.k.scrollElement)}function $b(a){var b=a.ba,b=b?Math.min(b*2,16):1;a.ba=b}k.na=function(){this.ya();this.terminate()};k.sb=function(){this.q();Zb(this)};
function cc(a){if(a.k.virtualReferrer)return h;a=(document.referrer||"").indexOf("://"+l.location.hostname+"/");return a!=-1&&a<9}function dc(a){a=a.k.virtualReferrer;if(!a&&(a=document.referrer||"")){var b=gb(a);if(b.protocol==="http:"||b.protocol==="https:")b.pathname=S(b.pathname),a=hb(b)}return encodeURIComponent(a)}function ec(a){a=a.k.title.slice(0,100);return encodeURIComponent(a)}function Vb(a){a=[dc(a),F("Width"),F("Height")];return ha(a)}
function fc(a){var b=[],c=a.F.B("_chartbeat4");c&&(o(c.split("::"),function(a){b.push(encodeURIComponent(a))}),a.F.remove("_chartbeat4"));return b}k.terminate=function(){this.J.terminate();G.S(this.ec);this.La!==g&&ia("load",this.La);C(this.Nb);var a=Xb;V()[a]=g;a=Yb;V()[a]=g};k.Z=function(){this.terminate();ia("unload",this.pb);this.pb=this.La=this.F=this.ga=this.k=i;this.J.Z();this.J=i;U.P.Z.call(this)};var Xb="d",Yb="n";function Wb(a,b){var c=V();return s(b)&&!s(c[a])?b:c[a]}function V(){s(l._cb_shared)||(l._cb_shared={});return l._cb_shared};function W(){this.T=[];this.Pa=[];this.Ga=r(this.Ga,this);"postMessage"in window&&u(window,"message",r(this.xc,this));this.Zb="_p_";this.Qa=j;u(l,"beforeunload",r(this.Gc,this));if(ib()>0){var a=r(this.Fa,this);V().a=a;var a="ad_debug",b="//static.chartbeat.com";Ka()&&(b="//static2.chartbeat.com");b=[b,"js"];Ka()&&(a+="dev");b.push("chartbeat_"+a+".js");Ja(b.join("/"))}U.call(this)}aa(W,U);k=W.prototype;
k.q=function(){W.P.q.call(this);var a=l.location;J(this.k,"pingServer","ping.chartbeat.net");J(this.k,"endServer","edge01.chartbeat.net");J(this.k,"title",document.title);J(this.k,"domain",a.hostname);this.k.domain=t(this.k.domain);J(this.k,"domainAd",this.k.domain);J(this.k,"path",Qb(!!this.k.useCanonical));J(this.k,"engaged",j);this.aa=this.k.adIdentifier||"data-cb-ad-id";this.ha=this.Ob=0;this.qc=function(){var a=q()-this.Ob;if(a<500){this.ha&&D(this.ha);var b=r(this.Y,this);this.ha=ua(b,500-a)}else this.ka||
this.Y()};this.pc=G.G("p",this.qc,this);this.oa={};this.ua=0;if((a=this.k.engagedAdFilters)&&a.length){var b=this;o(a,function(a){b.ma(a)})}this.Ca();this.Jc=G.G("g",this.vc,this);Lb();this.Uc=G.G("z",this.Rc,this);this.Pa=[]};k.vc=function(){var a=Ib.Lb(),b=a.Oa;if(b===1||b===2)this.Hb=G.G("e",this.mc,this),o(a.Jb,r(this.ma,this))};
k.Fa=function(a,b){var c=va(G,Oa),d=va(K,vb),e=r(function(){return{engagedAdFilters:this.oa,maxEngagedAdSpecificity:this.ua}},this);a.injectDependencies(c,d,e);b.injectDependencies(c);this.Gb=new a;zb=b;o(this.T,function(a){a.Fa()})};k.Gc=function(){this.Y(h)};k.ya=function(){this.F.update("_chartbeat4",["t="+this.Aa,"E="+this.J.X,"ad="+ka(gc(this,h)),"x="+bc(this),"c="+Math.round((q()-this.da)/600)/100,"y="+F("Height"),"w="+Ea()].join("&"),3600,g,g,1)};
function hc(a){return encodeURIComponent("ads."+a.k.domainAd)}function gc(a,b){var c=[];o(a.T,function(a){a=Bb(a);(!b||!(a.aw<=1&&a.ah<=1))&&c.push(Hb(a))});return c.concat(a.Pa).join("&")}var ic="h,p,u,d,g,g0,g1,g2,g3,g4,n,nc,f,c,x,m,y,o,w,j,E,v,r,vp,b,t,V,i,tz,l,,ad,z,zz,sn".split(",");k=W.prototype;
k.Y=function(a){this.Ma++;var b=this.Ga();b.ad=ka(gc(this));this.Ob=q();this.ha&&D(this.ha);Qb(!!this.k.useCanonical);if(this.ka)this.ka=j,b.i=ec(this);this.k.virtualReferrer&&(b.vp=1);var c=0;a?(b.zz=1,a=this.k.endServer):(b.z=fc(this),c=Math.round((this.ba+2)*15E3/1E3),a=this.k.pingServer);b.j=c;b.l=Pb(this.F)?1:"";this.J.ja=0;this.za("https://"+a+"/ping/ad?"+fb(b,ic))};
k.Ga=function(){var a=ac(this),b=l.location;a.h=hc(this);a.p=encodeURIComponent(this.k.path);a.u=this.Da;a.d=ka(t(b.hostname));cc(this)?a.v=dc(this):a.r=dc(this);return a};function jc(a){var b=Aa(a.aa,"div");o(b,function(b){if(!kc(a,b)){var d=new N(b,a.Ga);a.T.push(d);d.Ca();if(b=E("data-cb-engaged-seconds",b))d=Gb(d),d[P]=parseInt(b,10),a.ma(d)}})}function kc(a,b){var c;o(a.T,function(a){if(a.ea===b||a.M===b)return c=a,j});return c}
k.Ca=function(){var a=Wb("c");jc(this);var b=this;o(this.T,function(c){c.Ca();var d=c.ea;if(a&&a[d]){var e=-1;o(a[d],function(a,d){if(a.e===c.M)return a.c(b.Aa,hc(b)),e=d,j});e>-1&&a[d].splice(e,1)}})};k.ob=function(){W.P.ob.call(this);jc(this)};k.xc=function(a){this.Pb(z(a.data)?pa(a.data):{},a.source)};
k.Pb=function(a,b){if(a.cbType!=="campaignMessage")return j;var c=b;if(c.parent!=window){for(var d=0;c.parent!=window&&d<10;)c=c.parent,d++;if(d>=10)return j}jc(this);var d=document.getElementsByTagName("iframe"),e=g;o(d,function(a){if(a.contentWindow===c)return e=a,j});if(!e)return j;var f=e.getAttribute(this.aa),n;if(f===i){n=Ba(e,this.aa);if(!n)return j;f=n.getAttribute(this.aa)}else n=e;var p=g;o(this.T,function(a){if(f===a.ea&&n===a.M)return p=a,j});if(p===g)return j;Eb(p,a,e);if(d=a[P]){var m=
Gb(p);m[P]=parseInt(d,10);this.ma(m)}d=["cbdata::ack",this.Aa,hc(this)].join("::");"postMessage"in b&&b.postMessage(d,"*");return d};k.ma=function(a){if(a&&v(a[P])&&!isNaN(a[P])){var b={};o(Fb,function(c){if(z(a[c])||c===P)b[c]=a[c]});var c=wa(b).length;this.ua=Math.max(this.ua,c);this.oa[c]=this.oa[c]||[];var c=this.oa[c],d=j;o(c,function(a){var c=h;o(a,function(a,d){if(d!==P)return c=b[d]===a});(d=c)&&(a[P]=b[P]);return!d});d||c.unshift(b);this.Gb&&this.Gb.update()}};
k.Kc=function(a,b){if(!a)return j;var c=l.document.getElementById(b);if(!c)return j;var d;c.getAttribute(this.aa)&&(d=kc(this,c));var e=this;if(!d){var f=Aa(this.aa,"div",c);o(f,function(a){if(d=kc(e,a))return j})}d||(c=Ba(c,this.aa))&&(d=kc(this,c));if(!d)return j;d.Mb=a;return h};
k.mc=function(a){if(a&&this.ua!==0){var b=a.Mb,c=this.k.engagedAdCallback;b&&!c&&(c=sa);if(c)for(var d=this,e=Gb(a),f=e[P],n=this.ua,p=j;n>0&&!p;)o(this.oa[n]||[],function(m){p=h;o(m,function(a,b){if(b!==P)return p=a===e[b]});if(p){m=m[P];if(m===-1)return j;if(m===f)e.element=a.M,c(e,f),b&&a.mb==j&&(a.kb?lc(d,a):mc(d,a));return j}}),n--}};k.Ic=function(a){if(a&&(a=kc(this,a))){a.Xa=1;var b=Bb(a);this.Pa.push(Hb(b));a.refresh();a.Wa=1}};
function mc(a,b){b.Xa=2;var c=Bb(b);a.Pa.push(Hb(c));b.refresh();c=b.Mb;try{c.setTargeting("_cbr","1"),l.googletag.pubads().refresh([c]),b.Wa=2,c.setTargeting("_cbr","0")}catch(d){}}
k.Rc=function(a,b){for(var c=pa(this.F.B("_chartbeat7")),d=parseInt(c[a.vzcid],10)||0,e={1:h,5:h,15:h,30:h,60:h,100:h};b--;)if(d++,e[d+""]){var f=a,n=d+"second"+(d!==1?"s":""),p=fa(ea());da("http://ohlone.vizu.com/a.gif?vzcid="+f.vzcid+"&vzadid="+n+"&vzsid="+f.vzsid+"&ord="+p)}c[a.vzcid]=d;this.F.create("_chartbeat7",oa(c),94608E3)};function nc(a){var b=j;o(a.T,function(a){if(a.Ja)return b=h,j});return b}function lc(a,b){(b.Ja||!nc(a))&&o(a.T,function(b){b.kb&&mc(a,b)})}
k.terminate=function(){G.S(this.pc);G.S(this.Jc);G.S(this.Uc);this.Hb&&G.S(this.Hb);o(this.T,function(a){a.Z()});this.T=[];D(this.ha);W.P.terminate.call(this)};if(!l.pSUPERFLY_pub){var Y=new W,oc={addEngagedAdFilter:r(Y.ma,Y),refreshAd:r(Y.Ic,Y),updateCampaignData:r(Y.Ca,Y),registerGptSlot:r(Y.Kc,Y)};oc.evps=r(Y.na,Y);oc.svps=r(Y.sb,Y);"postMessage"in window!==h&&(oc.loadCampaign=r(Y.Pb,Y));l.pSUPERFLY_pub=oc;Zb(Y)};function pc(){var a=l.location.href,a=a.replace(/-{2,}/g,"-"),a=gb(a);a.pathname=S(a.pathname);return a}function qc(a){var b=R.B("_chartbeat6");if(!b)return i;var b=b.split("::"),c,d;if(b.length===1)c=b[0].split(","),d=0;else{var e,f=pc(),n=hb(f);o(b,function(a,b){var f=a.split(","),x=qa(n,decodeURIComponent(f[0]));if(x===0)return c=f,d=b,j;if(e===g||x<e)e=x,c=f,d=b})}b.splice(d,1);a="_chartbeat6="+b.join("::")+rc(a);document.cookie=a;return{dd:c[0],oc:c[1],Sc:c[2],origin:c[3]}}
function rc(a){var b="",c;if(!B(a))return b;a.Sb&&(c=new Date,c.setTime(c.getTime()+a.Sb),b+="; expires="+c.toGMTString());a.domain&&(b+="; domain="+a.domain);a.path&&(b+="; path="+a.path);return b}function sc(a,b){if(a===b)return h;for(var c=b.split("."),d=a.split(".");c.length;){if(d.length===0)return j;if(c.pop()!==d.pop())return j}return h};function tc(a,b){for(var c=b||document.documentElement,d=[],e=i,f=a,n,p,m,y,x,L;f&&f!==c;){n=f.nodeName.toLowerCase();e=f;p=e.nodeName;if((f=f.parentNode)&&f!==document.documentElement){m=f.children;y=0;for(x=0,L=m.length;x<L;x++){if(e===m[x]){n+="["+(1+x-y)+"]";break}m[x].nodeName!==p&&y++}}d.unshift(n)}return d.join("/")};function uc(){this.Zb="_t_";U.call(this)}aa(uc,U);k=uc.prototype;
k.q=function(){uc.P.q.call(this);kb(this.k);var a=l.location;J(this.k,"mabServer","mabping.chartbeat.net");J(this.k,"title",document.title);J(this.k,"domain",a.hostname);J(this.k,"path",Qb(!!this.k.useCanonical));this.sa=t(a.hostname);this.k.domain=t(this.k.domain);var b=this.k,a=b.topStorageDomain,b=b.domain,c=l.location.hostname;this.Pc=a?a:sc(c,b)?b:c.replace(/^www\./,"");this.xb=this.ab=this.bb="";this.pa=this.Ia=j;a=qc({domain:"."+this.Pc,Sb:6E4,path:"/"});if(a!==i)this.bb=a.origin,this.ab=a.oc,
this.xb=a.Sc,this.Ia=h;this.Tb=0;this.Sa=i;a=r(this.yc,this);for(b=Wb("m")||[];b.length;)a(b.shift());a={push:a};V().m=a};k.Y=function(){var a=this.J.X,b=vc(this),c,d,e;if(this.Ia)c=this.bb,d=this.ab,e=this.xb,this.za(b+"&x="+d+"&v="+e+"&xo="+c+"&e="+a);!this.pa&&this.Sa&&wc(this,this.Sa);this.pa=h};k.Ra=function(){var a=l._sf_startpt,b=l._sf_endpt;if(v(a))this.qb=v(b)?b-a:q()-a;H.q();if(this.Ia)a=r(this.wa,this),this.Nb=ta(a,500);this.wa()};
k.wa=function(){var a,b;this.pa?(a=this.J.X,b=this.Tb*15,a-b>=15&&(this.Y(),this.Tb+=1),a>=45&&this.terminate()):this.Y()};function vc(a){var b=a.k;return(l.location.protocol||"http:")+"//"+b.mabServer+"/ping/mab?h="+encodeURIComponent(b.domain)+"&p="+encodeURIComponent(b.path)+"&d="+encodeURIComponent(a.sa)+"&u="+a.Da+"&c="+Math.round((q()-a.da)/600)/100}k.ya=function(){};
k.Oc=function(a){var b=a.d,c=i;b!==i&&(c={Xb:b.s,Bc:b.l,Rb:b.m});a={status:a.s,data:c,code:a.c,message:a.m};this.pa?wc(this,a):this.Sa=a};function wc(a,b){var c=vc(a),d=b.status,e=b.data;if(d=="s"&&e!==i){if(!e.Bc){var f=r(a.za,a);B(e.Xb)&&o(e.Xb,function(a,b){f(c+"&x="+b+"&v="+a+"&e=-1")});Object.prototype.toString.call(e.Rb)==="[object Array]"&&o(e.Rb,function(a){f(c+"&mt=e&me=3&x="+a)})}}else d=="e"&&a.za(c+"&mt=e&me="+b.code)}
k.yc=function(a,b){for(var c=0,d=arguments.length;c<d;c++){var a=arguments[c],e=a.shift();e==="t"?this.Oc.apply(this,a):e==="v"&&this.Mc.apply(this,a)}};k.na=function(){V().m=[];s(this.yb)&&this.yb();uc.P.na.call(this)};k.Mc=function(a){this.yb=a};k.terminate=function(){this.yb=this.pa=this.Ia=this.xb=this.ab=this.bb=g;this.Sa=i;uc.P.terminate.call(this)};if(!l.pSUPERFLY_mab){var xc=new uc,yc={};yc.evps=r(xc.na,xc);yc.svps=r(xc.sb,xc);l.pSUPERFLY_mab=yc;Zb(xc)};var zc,Ac,Bc;function Dc(a){if(a.origin==="https://chartbeat.com"&&(a=String(a.data),a.indexOf("_cb_hud_version=")===0&&(a=a.substr(16),Ec(),a!=="NONE"))){var a=a.indexOf("HUD2.")===0?a.substr(5):"OLD",b="https://static.chartbeat.com/js/inpage.js";a!=="OLD"&&(b="https://static2.chartbeat.com/frontend_ng/hud/hud-inpage/hud-inpage-"+a+".js");Ja(b)}}function Ec(){D(Ac);Ac=g;ia("message",Dc);Bc&&Bc.parentNode&&Bc.parentNode.removeChild(Bc);Bc=g};function Fc(){var a=l._sf_async_config&&l._sf_async_config.domain;if(a&&!zc){zc=h;a="https://chartbeat.com/publishing/hud2/versioninfo/?host="+encodeURIComponent(a);u(l,"message",Dc);Ac=ua(Ec,1E4);var b=s(g)?g:{};b.src=a;a=Ia("iframe",b);a.style.display="none";s(g)?g.appendChild(a):document.body&&document.body.appendChild(a);Bc=a}}
function Gc(a){if(/[\/.]chartbeat\.com$/.test(a.origin)){var b=Q.D(h),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Fc(),ia("message",Gc))}};function Z(){"postMessage"in window&&u(l,"message",r(this.wc,this));U.call(this);jb("_cbq",r(this.Vb,this))}aa(Z,U);Z.prototype.q=function(){Z.P.q.call(this);this.Va=i;kb(this.k);var a=l.location;J(this.k,"pingServer","ping.chartbeat.net");J(this.k,"title",document.title);J(this.k,"domain",a.hostname);this.k.path=this.k.path?S(this.k.path):Qb(!!this.k.useCanonical);this.sa=t(a.hostname);this.k.domain=t(this.k.domain);this.gc=G.G("c",this.Ec,this);this.hc=G.G("r",this.Fc,this);this.ia=i};
Z.prototype.dc=function(a){this.Va=a};Z.prototype.ya=function(){this.F.update("_chartbeat4",["t="+this.Aa,"E="+this.J.X,"x="+bc(this),"c="+Math.round((q()-this.da)/600)/100,"y="+F("Height"),"w="+Ea()].join("&"),3600,g,g,1)};var Hc="h,p,u,d,g,g0,g1,g3,g4,n,nc,f,c,x,m,y,o,w,j,R,W,I,E,e,v,r,vp,K,l1,KK,PA,b,A,_c,_m,t,V,z,i,L,tz,l,,sn,C,eS,eM,eD,eK,eR".split(",");k=Z.prototype;
k.Y=function(a){this.Ma++;var b=ac(this),c=this.J.ja;b.h=encodeURIComponent(this.k.domain);b.p=encodeURIComponent(this.k.path);b.u=this.Da;b.d=encodeURIComponent(this.sa);b.j=Math.round((this.ba+2)*15E3/1E3);b.R=0;b.W=0;b.I=0;var d=b.c*6E4+this.da;b.eD=H.qa("mousedown",d);b.eM=H.qa("mousemove",d);b.eK=H.qa("keydown",d);b.eR=H.qa("resize",d);b.eS=H.qa("scroll",d);H.Lc();H.fc()?b.W=1:this.k.reading&&+this.k.reading||c>0||b.c<0.09?b.R=1:b.I=1;b.e=c;c=cc(this);if(this.ka)this.ka=j,c?this.ia=Ic(this):
b.r=dc(this),b.i=ec(this),d=this.k.hudTrackable,d!==g&&(b.L=d?"1":"0"),this.k.alias&&(b.PA=encodeURIComponent(this.k.alias));if(c){if(this.ia){if(b.v=encodeURIComponent(this.ia.path),b.K=Jc(this.ia),this.ia.nb>1)b.l1=this.ia.nb}else b.v=dc(this);this.k.virtualReferrer&&(b.vp=1)}b.A=this.Va?this.Va:"";b._c=db("utm_campaign",this.k.campaignTag);b._m=db("utm_medium",this.k.mediumTag);b.z=fc(this);b.C=this.k.mobileApp?1:"";b.KK=a?Jc(a,h):"";b.l=Pb(this.F)?1:"";this.J.ja=0;this.za((l.location.protocol||
"http:")+"//"+this.k.pingServer+"/ping?"+fb(b,Hc))};
k.wc=function(a){var b=this.k;if(a.origin==="http://"+(b.playerdomain||this.sa)){var c=a.data;z(c)&&c.indexOf("cbqpush::")===0?(a=c.split("::"),a.length==3&&(a=a.slice(1),a[0].indexOf("_")===0&&this.Vb(a))):c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&uid="+encodeURIComponent(b.uid)+"&path="+encodeURIComponent(b.path)+"&title="+ec(this)+"&referrer="+dc(this)+"&internal="+(cc(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.sa)+"&utoken="+this.Da,a.source.postMessage(b,"*"))}};
k.Vb=function(a){a[0]==="_demo"&&this.k._demo?this.k._demo=this.k._demo+"%2C"+a[1]:this.k[a[0]]=a[1];this.ba=0};function Kc(a){a=a.replace(/-{2,}/g,"-");a=gb(a);a.pathname=S(a.pathname);return a}k.Ec=function(a){Lc(this,a,"c")};k.Fc=function(a){Lc(this,a,"r")};
function Lc(a,b,c){if(a.Qa&&q()-a.da>=a.lb)a.terminate();else{var d=b.href||"",d=Kc(d);if(!(d.hostname!==l.location.hostname||d.protocol.indexOf("http")!==0)){var d=hb(d),e=Fa(b,function(a){return a.id}),f=tc(b,e);e&&(f&&(f="/"+f),f="*[@id='"+e.id+"']"+f);e=fa(f);b=sb(b,g,h);c={left:b.x,top:b.y,path:a.k.path,href:d,Bb:e,Ab:f,rb:c,nb:0};a.Y(c);a.F.update("_chartbeat5",Mc(c),60,j,g,5,function(a){a=a.split(",");return a[2]+","+a[3]})}}}
function Jc(a,b){var c=[a.left,a.top,a.Bb,encodeURIComponent(a.Ab),a.rb];b&&c.push(encodeURIComponent(a.href));return c.join("::")}function Mc(a){var b=encodeURIComponent(a.Ab),b=b.replace(/-/g,"%2D");b.length>512&&(b="");return[a.left,a.top,encodeURIComponent(a.path),encodeURIComponent(a.href),a.Bb,b,a.rb].join(",")}
function Ic(a){var b=a.F.B("_chartbeat5");if(!b)return i;var c=b.split("::"),b=c.length,d,e;if(b===1)d=c[0].split(","),e=0;else{var f,n=Kc(l.location.href),p=hb(n);o(c,function(a,b){var c=a.split(","),n=qa(p,decodeURIComponent(c[3]));if(n===0)return d=c,e=b,j;if(f===g||n<f)f=n,d=c,e=b})}c.splice(e,1);a.F.create("_chartbeat5",c.join("::"),60);(a=d[5])?(a=a.replace(/%2D/g,"-"),a=decodeURIComponent(a)):a="";return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),Bb:d[4]||"",Ab:a,rb:d.length>6?d[6]:"c",
nb:b}}k.terminate=function(){G.S(this.gc);G.S(this.hc);Z.P.terminate.call(this)};if(!l.pSUPERFLY){var Nc=new Z,Oc={};l.pSUPERFLY=Oc;var Pc=l.pSUPERFLY_mab,$=l.pSUPERFLY_pub,Qc=[];Pc&&Qc.push(Pc);if($)Qc.push($),$.addEngagedAdFilter&&(Oc.addEngagedAdFilter=$.addEngagedAdFilter),$.refreshAd&&(Oc.refreshAd=$.refreshAd),$.registerGptSlot&&(Oc.registerGptSlot=$.registerGptSlot),jb("_cba",function(a){a()});Oc.virtualPage=function(a,b){if(!Va){var c=l._sf_async_config;c.virtualReferrer=l.location.protocol+"//"+c.domain+c.path;c.path=S(a);b&&(c.title=b);Nc.na();o(Qc,function(a){a.evps()});
Nc.sb();o(Qc,function(a){a.svps()})}};Oc.activity=r(Nc.dc,Nc);Zb(Nc);var Rc=Q.D(h);if(Rc)if(Rc.getItem("_cb_ip")){var Sc=l.location;(!/^(.+[.])?chartbeat\.com$/.test(Sc.hostname)?0:/^\/publishing\/(overlay|hud|mab)\//.test(Sc.pathname))||Fc()}else u(l,"message",Gc)};})();
