//tealium universal tag - utag.138 ut4.0.201506020133, Copyright 2015 Tealium.com Inc. All Rights Reserved.
var googletag=googletag||{};googletag.cmd=googletag.cmd||[];try{(function(id,loader,u){try{u=utag.o[loader].sender[id]={}}catch(e){u=utag.sender[id]};u.ev={'view':1};u.qsp_delim="&";u.kvp_delim="=";u.divid="AD_CP";u.slot="/2/interactive.wsj.com/topcirc";u.height="28";u.width="165";u.collapseEmptyDivs="true";u.map={"gpt_circ":"setTargeting_slot","gpt_slot":"slot"};u.extend=[];u.send=function(a,b,c,d,e,f){if(u.ev[a]||typeof u.ev.all!="undefined"){u.setTargeting={};for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f]=="slot"||e[f]=="gptSlots"||e[f]=="height"||e[f]=="width"||e[f]=="collapseEmptyDivs"||e[f]=="setTargeting_slot"||e[f]=="setTargeting"){u[e[f]]=b[d]}else{u.setTargeting[e[f]]=b[d]}}}}
if(u.networkcode&&u.adunit){u.slot="/"+u.networkcode+"/"+u.adunit;}
u.gptSlots=u.gptSlots||((u.width===""&&u.height==="")?[[u.slot,null,u.divid]]:[[u.slot,[parseInt(u.width),parseInt(u.height)],u.divid]]);googletag.cmd.push(function(){for(f=0;f<u.gptSlots.length;f++){var slot;if(u.gptSlots[f][1]==null||u.gptSlots[f][1]=="OutOfPageSlot"){slot=googletag.defineOutOfPageSlot.apply(this,[u.gptSlots[f][0],u.gptSlots[f][2]]).addService(googletag.pubads());}else{slot=googletag.defineSlot.apply(this,u.gptSlots[f].slice(0,3)).addService(googletag.pubads());}
var data=u.gptSlots[f][3]||u.setTargeting_slot||{};for(d in data){slot.setTargeting(d+'',data[d])}
if(u.collapseEmptyDivs=="true"){slot.setCollapseEmptyDiv(true);}}
googletag.pubads().enableSingleRequest();googletag.enableServices();});googletag.cmd.push(function(){for(f in u.setTargeting){googletag.pubads().setTargeting(f,u.setTargeting[f]);}
for(f=0;f<u.gptSlots.length;f++){if(document.getElementById(u.gptSlots[f][2])){googletag.display(u.gptSlots[f][2]);}}});}}
try{utag.o[loader].loader.LOAD(id)}catch(e){utag.loader.LOAD(id)}})('138','wsjdn.wsjarticles');}catch(e){}
