//tealium universal tag - utag.165 ut4.0.201507301641, Copyright 2015 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.event_lookup={"reportViewContent":"reportViewContent","reportSearch":"reportSearch","reportAddToCart":"reportAddToCart","reportAddToWishlist":"reportAddToWishlist","reportInitiateCheckout":"reportInitiateCheckout","reportAddPaymentInfo":"reportAddPaymentInfo","reportPurchase":"reportPurchase","reportLead":"reportLead","reportCompleteRegistration":"reportCompleteRegistration","Custom":"Custom"};u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,g;u.data={"qsp_delim":"&","kvp_delim":"=","base_url":"//connect.facebook.net/en_US/fbevents.js","fb_pixel_id":"772935086090481","custom_data":{},"custom_event":"","product_id":[],"product_category":[],"product_unit_price":[]};c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("custom_data.")===0){u.data.custom_data[[e[f].substr(12)]]=b[d];}else{u.data[e[f]]=b[d];}}}else{h=d.split(":");if(h.length===2&&b[h[0]]===h[1]){if(u.map[d].indexOf("Custom.")===0){g=u.map[d].substr(7);}else{g=""+u.event_lookup[u.map[d]];}
if(g!==""){b._cevent=g;}}}}
u.data.order_id=u.data.order_id||b._corder||"";u.data.order_subtotal=u.data.order_subtotal||b._csubtotal||"";u.data.order_currency=u.data.order_currency||b._ccurrency||"";if(u.data.product_id.length===0&&b._cprod!==undefined){u.data.product_id=b._cprod.slice(0);}
if(u.data.product_category.length===0&&b._ccat!==undefined){u.data.product_category=b._ccat.slice(0);}
if(u.data.product_unit_price.length===0&&b._cprice!==undefined){u.data.product_unit_price=b._cprice.slice(0);}
u.loader_cb=function(a,b,c){u.initialized=true;g={};if(u.data.order_id||b._cevent==="reportPurchase"){b._cevent="reportPurchase";g={"currency":u.data.order_currency,"value":u.data.order_subtotal||"0.00"};}else if(b._cevent==="reportViewContent"||b._cevent==="reportAddToCart"){g={"price":u.data.product_unit_price[0]||"0.00","product_id":u.data.product_id[0]||"","product_category":u.data.product_category[0]||""};}else if(b._cevent==="reportLead"){g={"currency":u.data.order_currency,"value":u.data.order_subtotal||"0.00"};}else if(b._cevent&&!u.event_lookup[b._cevent]){if(!u.data.custom_data.event){u.data.custom_data.event=b._cevent;}
b._cevent="reportCustomEvent";g=u.data.custom_data;}
if(b._cevent){fbq(b._cevent,g);}};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b,data.c);}};if(u.initialized){u.loader_cb(a,b,c);}else{u.queue.push({"data":u.data,"a":a,"b":b,"c":c});if(!u.scriptrequested){u.scriptrequested=true;(function(f,b,e,v,n,t,s){n=window.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};n.version='1.0';n.pixelId=e;n.queue=[];t=f.createElement(b);t.async=true;t.src=v;s=f.getElementsByTagName(b)[0];s.parentNode.insertBefore(t,s)}(document,'script',u.data.fb_pixel_id,u.data.base_url));fbq('reportPageView');u.callBack();}}
}};utag.o[loader].loader.LOAD(id);}("165","wsjdn.wsjarticles"));}catch(error){utag.DB(error);}
